In [ ]:
import numpy as np 
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Churn_Modelling.csv')
df.shape

(10000, 14)

In [ ]:
df.drop(['CustomerId','RowNumber','Surname'], axis = 'columns', inplace =True)

In [ ]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
#one hot encoding
df = pd.get_dummies(data = df, columns=['Geography'])
df.dtypes

CreditScore            int64
Gender                object
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France       uint8
Geography_Germany      uint8
Geography_Spain        uint8
dtype: object

In [ ]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
df['Gender'].replace(['Male', 'Female'],[1, 0], inplace= True)

In [ ]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
#separate outcome or target col
X = df.drop(['Exited'], axis=1)
y = df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

# feature scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(12, input_shape=(12,),activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5976 - accuracy: 0.6628
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4396 - accuracy: 0.8119
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4111 - accuracy: 0.8267
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3898 - accuracy: 0.8382
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3703 - accuracy: 0.8470
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8537
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8586
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3434 - accuracy: 0.8587
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8610
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accura

In [ ]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 1s 4ms/step - loss: 0.3311 - accuracy: 0.8625


[0.3311230540275574, 0.862500011920929]

In [ ]:
yp = model.predict(X_test)

63/63 [==============================] - 0s 1ms/step


In [ ]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.52      0.61       405

    accuracy                           0.86      2000
   macro avg       0.80      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [ ]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

In [ ]:
cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1514,   81],
       [ 194,  211]], dtype=int32)>

In [ ]:
tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1514,   81],
       [ 194,  211]], dtype=int32)>